### ISSUE TITLE
On upgrade: discrepancy between SiteConfig setting and mode selected

### ISSUE THREAD

**Issue by JamesDPC** [xini/silverstripe-robots#1]
Hi

Upgrading a project to innoweb/silverstripe-robots:^3.1.0 from 1.x and have noticed that while the DB has an empty RobotsMode after the update:

```
mysql> SELECT RobotsContent, RobotsMode FROM SiteConfig\G
*************************** 1. row ***************************
RobotsContent: NULL
   RobotsMode: NULL
```

.. the site settings selection shows Allow all:

![image](https://user-images.githubusercontent.com/69664712/152899917-80756123-eba6-4a18-859d-1936622efcd6.png)

..and the robots.txt for the project shows Disallow:

```
User-agent: *
Disallow: /
```

The incorrect default selection of 'allow' looks to be from the setting of the RobotsMode value as the first option key here:
```php
        $currMode = $this->getOwner()->RobotsMode;
        if (!$currMode || !isset($options[$currMode])) {
            reset($options);
            $this->getOwner()->RobotsMode = key($options);
        }
```

If the RobotsMode is not set, I think the field should be assigned the value of `getDefaultRobotsMode()` ?
That would make the above code redundant :thinking:

Cheers
James

**Comment by xini** [comment]
Hi James,

Thanks. Yes, that is weird. I'll have a look tomorrow at getting better default values after an upgrade. 

Cheers

**Comment by xini** [comment]
Version 3.1.1 fixes this issue. Thanks again.
